### ISSUE TITLE
Allow url be passed as argument

### ISSUE THREAD

**Issue by carlosqsilva** [philippta/flyscrape#13]
It would be nice to pass the url as argument to overwrite `config.url`

example:

wrote this script, but now i want use for a different url in the same domain

```js
export const config = {
  url: "https://example.com/HXXluMZo",
};
export default function({ doc, absoluteURL }) {
  return links = doc.find("a.box-link").map(link => absoluteURL(link.attr("href")))
}
```

```bash
$ fly run example.js --url example.com/ywwU2do6
```

**Comment by philippta** [comment]
This is a good idea I also had in my head. Ideally it should be possible to use cli flags to override or set any configuration option.

**Comment by philippta** [comment]
@carlosqsilva 
Support for CLI arguments has been added. You can now override set or overridea any config option via a CLI flag, e.g:
```
flyscrape run example.js --url "http://other.com"

flyscrape run example.js --proxies "http://someproxy:8043"

flyscrape run example.js --depth 5 --follow ".next-button > a"
```

To use this latest feature, make sure to compile and install flyscrape from souce, as there's no precompiled binary yet.

```
go install github.com/philippta/flyscrape/cmd/flyscrape@master
```
