### ISSUE TITLE
`NaN` quietly breaks all data

### ISSUE THREAD

**Issue by remy** [philippta/flyscrape#17]
I've just found that if I return `NaN` (unwittingly), it causes the entire response to become empty.

I've not looked at the Go source (and though I can probably read it, I've not programmed anything in anger with Go, so don't entirely trust myself), but my guess would be that the conversion is quietly failing and causes all data to be ejected.

Here's how to replicate in a script.mjs:

```js
export const config = {
  url: 'https://example.com',
};

export default function () {
  return Array.from({ length: 10 }).map(() => ({
    a: 'test',
    b: NaN,
  }));
}
```

Result:

```
$ flyscrape run script.mjs
[

]
```

If I wrap the return value in a serialise/deserialise then it works again (but only because `NaN` gets mapped to `null`).

**Comment by philippta** [comment]
Thanks for reporting. The issue got fixed in #21 by running the return value through the JavaScript serialise/deserialise.
