### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BluesYoung-web** [philippta/flyscrape#19]
**Is it only support ssr pages?**

**Comment by leopku** [comment]
I got codes below worked with json endpoint. Maybe it can wokr with rss endpoint by little changing.

```js
import http from "flyscrape/http";

export default function ({ url }) {
  const resp = http.get(url);
  const result = resp.body;
  console.log(result);
  return { result };
}
```

```shell
flyscrape run httpbin.js --url 'http://httpbin.org/anything'
```

**Comment by BluesYoung-web** [comment]
I think you maybe misunderstanding. What i really want to ask is: 'If i request a page that rendered in browser instead of rendered in server, does it still work?'

**Comment by philippta** [comment]
Flyscrape currently does not support browser rendering.

As a possible workaround you could try and integrate a paid services like ScrapingBee, that offer browser rendering by setting them as a proxy ([Scraping Bee Proxy Mode](https://www.scrapingbee.com/documentation/#proxy-mode)).

**Disclaimer: I am not affiliated with them or have tried this out.**

**Comment by philippta** [comment]
I am currently working on a hosted proxy service that can render websites in Chrome and I am looking for some testers.

Let me know if you are interested and I can share the details.
