### ISSUE TITLE
Errors in Getting Started docs page

### ISSUE THREAD

**Issue by altern8tif** [philippta/flyscrape#26]
Some errors on the [Getting Started](https://flyscrape.com/docs/getting-started/) docs page.  

Should be `const meta = post.next(1);` instead of `const meta = link.next();`

![CleanShot 2023-12-06 at 5  29 08](https://github.com/philippta/flyscrape/assets/5793364/9409e6bc-6610-4089-a76b-ebaa0f5425ae)

I think the docs might have been removed from the repo, hence didn't submit a PR.

**Comment by apainintheneck** [comment]
I ran into the same thing. Maybe it's just that Hacker News has updated their website since the doc was written.

**Comment by philippta** [comment]
Thanks for reporting. Docs are updated.

It should have been this, just like in [examples/hackernews.js](https://github.com/philippta/flyscrape/blob/master/examples/hackernews.js#L14):
```
const meta = post.next();
```
