### ISSUE TITLE
Random User-Agent

### ISSUE THREAD

**Issue by philippta** [philippta/flyscrape#35]
The headers module should get a feature that allows for randomized user-agents per request.

The feature should be enabled when the following configuration is provided.
```js
headers: {
    "User-Agent": "random",
}
```

Ref:
- https://github.com/gocolly/colly/blob/master/extensions/random_user_agent.go

**Comment by rafiramadhana** [comment]
can I work on this enhancement @philippta ? thanks

**Comment by philippta** [comment]
@rafiramadhana Please go ahead. Two things:

- The list doesn’t seem to have been updated since 2023/05. Make sure to check for new versions and add them to the list.
- I think just the desktop versions of Chrome, Firefox, Edge and Opera will be enough. Bonus points will be given if you can add Safari. Ignore the pixel ones. 

I am also thinking if it would be beneficial to enable random user agents by default, and only make it static if configured in the config. Any opinion?

**Comment by philippta** [comment]
Hey @rafiramadhana, any updates on this?

**Comment by rafiramadhana** [comment]
@philippta Sry I haven't put any progress on this.

Feel free to assign this to someone else if needed. Thanks.
