### ISSUE TITLE
Authentication?

### ISSUE THREAD

**Issue by rothgar** [philippta/flyscrape#4]
I may have missed it, but is there a way to query a URL with auth cookies or credentials?

**Comment by philippta** [comment]
There is an example demonstrating how you can login to a website before the scraping starts. It will store any cookie returned by the website for subsequent requests.

[examples/hackernews_login.js](https://github.com/philippta/flyscrape/blob/master/examples/hackernews_login.js)

Setting a Bearer Token or HTTP Basic Auth is not yet supported.
