### ISSUE TITLE
queue is full, can't add url

### ISSUE THREAD

**Issue by dynabler** [philippta/flyscrape#42]
I get the message `queue is full, can't add url` when running Flyscrape. The JS file has 5000+ start URLs. After the scraping was finished, I counted the data, and it only got 1024 URL's. Am I missing something? Or doing wrong?

**Comment by philippta** [comment]
This is currently a technical limitation I had to go with. But it can be increased in a later release.

If you have the ability to compile from source, you can increase this number here:
https://github.com/philippta/flyscrape/blob/f2d36972b238cb6bfe2548ec59508bbd83be0a05/scrape.go#L81

**Comment by dynabler** [comment]
No ability to compile it from source, couldn't solve the answer from here: #40 

I also used import urls, and that has its limits as well. I get the same message `queue is full, can't add url`. At least one of them should have a higher limit.

25000 URLs is a safe limit from my experience. The output still needs to be checked manually, so most people work in batches of 10K to 20K.

Looking forward to the release that fixes this.

**Comment by philippta** [comment]
Fixed in the latest release [v0.7.2](https://github.com/philippta/flyscrape/releases/tag/v0.7.2). You can now add up to a million urls.

https://github.com/philippta/flyscrape/blob/c796f4164c13e30135246c08304acd7142673f60/scrape.go#L83
