### ISSUE TITLE
cache: failed to insert cache key

### ISSUE THREAD

**Issue by dynabler** [philippta/flyscrape#48]
Got this error when running Flyscrape

`cache: failed to insert cache key "GET https://example.com/shoes": UNIQUE constraint failed: cache.key`

Error was caused by a change in url. When writing the script it was `https://example.com/shoes`, but in the meantime it changed to `https://example.com/amazing-shoes`

Perhaps an idea to have it output a more clear message like that `"WARNING": "Forgot to call text(), html() or attr()?"`

**Comment by philippta** [comment]
Unfortunately I can not replicate this issue. Could you add a bit more detail or a possible script that produces this?

In any case, the message you're seeing is only a warning, so it does not interrupt the scraping process.
