### ISSUE TITLE
Can this be used for downloading files in parallel?

### ISSUE THREAD

**Issue by TACIXAT** [philippta/flyscrape#5]
Can this be used for downloading files in parallel?

For example, if I wanted to download 400 gb of image embeddings from - https://deploy.laion.ai/8f83b608504d46bb81708ec86e912220/embeddings/img_emb/

**Comment by philippta** [comment]
Unfortunately this feature is not yet supported.

Tracked under:
- #6

**Comment by brianlow** [comment]
[axle](https://github.com/axel-download-accelerator/axel) can download a list of urls. It can download a single file in parallel so I suspect it will download multiple urls in parallel

Some other options c/o chatgpt

> GNU Parallel: This is a powerful tool for running jobs in parallel. You can use it to run multiple wget commands at once. Here's a basic example: `cat urls.txt | parallel -j 10 wget`. This command reads URLs from a file urls.txt and uses GNU Parallel to run 10 wget jobs simultaneously.

> xargs: Another option is to use xargs with the -P flag for parallel execution. For example: `cat urls.txt | xargs -n 1 -P 10 wget`. This runs wget for each URL in urls.txt, with up to 10 downloads in parallel.

**Comment by TACIXAT** [comment]
Thanks for these. I am a Windows user and a bit of a command prompt purist
these days (to force myself to learn).

I usually just implement scraping and downloaders in Python. Been meaning
to throw together a parallel downloader in Go. Would be a cool addition
here, I'll give this a try next time I am scraping.

**Comment by philippta** [comment]
File downloads have been added.

**Example:** https://github.com/philippta/flyscrape/blob/master/examples/download.js
**API Reference:** https://github.com/philippta/flyscrape#file-downloads
