### ISSUE TITLE
README.md documentation page for configuration is a 404

### ISSUE THREAD

**Issue by o6uoq** [philippta/flyscrape#68]
The README.md has this:

> Below is an example scraping script that showcases the capabilities of flyscrape. For a full documentation of all configuration options, visit the [documentation page](https://github.com/philippta/flyscrape/blob/master/docs/readme.md#configuration).

The [documentation page](https://github.com/philippta/flyscrape/blob/master/docs/readme.md#configuration) is broken (404).

**Comment by philippta** [comment]
Thanks, fixed!
