### ISSUE TITLE
Custom request headers

### ISSUE THREAD

**Issue by philippta** [philippta/flyscrape#9]
Custom request headers should be supported as a `headers` config option. 
A new `headers` module should be created for this.

Proposed example:
```javascript
export const config = {
  headers: {
    "Authorization": "Bearer ey...",
    "User-Agent": "Mozilla/5.0 ...",
  },
};
```

Ref:
- [flyscrape.RequestBuilder](https://github.com/philippta/flyscrape/blob/eae10426cd805ecc0a0459b61639e48e6cd913ad/module.go#L30-L32)

**Comment by rafiramadhana** [comment]
@philippta can i work on this? thanks

**Comment by rafiramadhana** [comment]
btw the idea of structuring code in modules is quite interesting

may i know your references (e.g. other repos or articles) regarding that modules code structuring?

**Comment by rafiramadhana** [comment]
> The bottom most adapter is applied first, which is what you want for headers.

sry, i'm a bit confused by this sentence

do you mean,

"The bottom most adapter (the `AdaptTransport` impl of `headers` module) is applied first (should be put at first in `moduleOrder`), which is what you want for headers."

```
 moduleOrder = []string{ 
 	// Transport adapters must be loaded in a specific order. 
 	// All other modules can be loaded in any order. 
        "headers",  // New `headers` module
 	"proxy", 
 	"ratelimit", 
 	"cache", 
 } 
```

**Comment by rafiramadhana** [comment]
> The last module is going to be the outer most in the onion like call chain, which can mangle the HTTP request first.
>
> Hope that makes sense 🙏

i see, thanks for the pointers
